### ISSUE TITLE
api config

### ISSUE THREAD

**Issue by fan159159** [mutonix/RefGPT#2]
api config 中的配置是怎么配置的，跟主流的api不太一样 ，有参考资料吗？谢谢

**Comment by mutonix** [comment]
api config的设置是直接请求的url的格式，因此也需要将主流的api转化成请求的url的格式

参考<https://platform.openai.com/docs/api-reference/chat/create>，主流应该是这样{"api-key": "XXXXXXXX", "request_url": "https://api.openai.com/v1/chat/completions"}

**Comment by tuqingwen** [comment]
请问如果我想用deepseek，应该如何设置api config呢？
